💄 메인 페이지 퍼블리싱
EFUB-EPRIS/EPRIS-Front pull request #17
Opened 2024-08-16 12:51 UTC by yoonjin-C

# 구현 기능
- 이슈 번호 작성 #9 
- 메인페이지, 메인페이지 모바일 버전 퍼블리싱 

# 구현 상태
- MainPage
![localhost_3000_ (2)](https://github.com/user-attachments/assets/97e48fc6-feb1-4cfc-bcbc-58cc3b97acca)
-MainPage 모바일
![localhost_3000_ (3)](https://github.com/user-attachments/assets/04fca1ad-98f0-4986-aed9-0c1ad3b0a5e4)

# 리뷰 요청사항
- 리뷰 담당자에게 전하고 싶은 말

2024-08-17 16:01 UTC, rwaeng requested changes
1. 1440px보다 클 때 화면 깨지는데 요부분 수정해주세요~!!
2. 색깔 변수 쓸 때 var(--white) 이런 식으로 쓰고 뒤에 색상 코드는 빼주세요! 크기 변수는 따로 선언한 게 없으니까 var 없이 그냥 rem 단위만 작성해주세요!!
3. 메인페이지 모바일일 때 사진이 다른 거 같은데 데스크탑 사진으로 줄이는 거 보다 저게 더 예쁜 거 같아서 모바일 크기일 때만 사진 바꾸는 건 어떨까요!? 
4.  메인페이지 사진 로딩이 생각보다 느린데 기회가 되면 개선하면 좋을 것 같슴다

2024-08-18 04:53 UTC, yoonjin-C commented on src/components/Main/Greetings.style.js
> +  `,
1440px보다 클 때 화면 깨지는데 요부분 수정해주세요~!! => 이부분 사진크기 자체가 1440px이라 cover해서 사용하게 되면 1440이상으로 브라우저 늘렸을때 사진 비율이 깨지게 되는데 그래도 꽉 차도록 수정할까요?

2024-08-18 08:44 UTC, rwaeng commented on src/components/Main/Greetings.style.js
> +  `,
![localhost_3001_](https://github.com/user-attachments/assets/2f1a5a66-1045-4d9b-bce7-5a53c17c4314)


화면 깨진다고 말한 게 1440px 보다 커지면 바깥에 마진 줘서 1440px보다는 안 늘어나야 하는데 바깥으로 튀어나오더라고요 사진은 괜찮습니다!!

2024-08-19 14:11 UTC, rwaeng requested changes
수정 후 재요청 주시면 머지하겠습니다~!!

2024-08-19 14:11 UTC, rwaeng commented on src/components/Admin/CardComponent.jsx
> +      />
이 부분 다시 input으로 바꿀 수 있을까요!?
제가 리뷰 남길 때 범위 선택을 잘못했더라고요 죄송합니다,,,

2024-08-19 14:11 UTC, rwaeng commented on src/components/Main/Greetings.style.js
> +    align-items: center;
```suggestion
    @media (max-width: 1279px) {
      align-items: center;
    }
```
이렇게 수정해야 모바일에서만 중앙정렬 될 듯 합니다

2024-08-19 19:46 UTC, yoonjin-C commented on src/components/Main/Greetings.style.js
> +    align-items: center;
앗 깜빡했네요 수정하겠습니다!

2024-08-19 20:02 UTC, yoonjin-C commented on src/components/Admin/CardComponent.jsx
> +      />
엇 아예 useResizeTextarea 훅을 사용하지 말라는 의미이신가요?! 
아니면 훅 사용은 유지하고 textarea -> input 으로만 수정할까요?

2024-08-20 05:40 UTC, rwaeng commented on src/components/Admin/CardComponent.jsx
> +      />
아! input 태그는 주로 텍스트 입력을 한 줄로 받을 때 쓰는데 이름이랑 직위는 여러 줄 쓸 정보가 없을 거 같아서 input태그로 수정하는 게 좋을 거 같아요
useResizeTextarea 훅은 textarea에 필요한 경우 사용하라고 만든 것이라 input 태그에는 사용 안 해도 되고 textarea에만 사용해주시면 됩니다!

2024-08-20 07:19 UTC, yoonjin-C commented on src/components/Admin/CardComponent.jsx
> +      />
아하 넹 수정하겠습니다

2024-08-20 07:49 UTC, rwaeng approved these changes
확인했습니다~

2024-08-20 07:50 UTC, merged