Main과 ClassInfo 뒷페이지에 디자인 QA 요구사항을 반영한다.
EFUB-EPRIS/EPRIS-Front pull request #58
Opened 2024-08-30 18:17 UTC by yoonjin-C

# 구현 기능
- 소개글 텍스트 크기 수정
- 그리팅 카드 디자인 수정
- 저장 후 버튼 비활성화
- 삭제시 삭제 재확인 문구 '삭제하시겠습니까?' 추가

# 구현 상태
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/f20e624a-c1cf-454e-a070-423d3ac45d0e">

# 리뷰 요청사항
- 리뷰 담당자에게 전하고 싶은 말

2024-08-31 15:05 UTC, rwaeng requested changes
![image](https://github.com/user-attachments/assets/96059ccc-f53c-4112-80e2-c9e502526c06)
1440px 보다 클 경우 텍스트가 삐져나옵니다!

모바일 사진 바꾼 거는 375px 이전까지만 적용되나요!?

2024-09-01 07:16 UTC, yoonjin-C commented
앗 모바일 사진 ~749까지로 수정하겠습니다

2024-09-01 13:11 UTC, yoonjin-C commented
수정사항 반영 완료했습니다

2024-09-01 13:19 UTC, rwaeng approved these changes
확인했습니다~!

2024-09-01 13:19 UTC, merged