[FE] 푸터 퍼블리싱을 한다.
EFUB-EPRIS/EPRIS-Front pull request #6
Opened 2024-08-11 15:49 UTC by yoonjin-C

# 구현 기능
- 이슈 번호 작성 #5 
- 푸터 및 푸터 모바일 퍼블리싱

# 구현 상태
푸터
<img width="1092" alt="image" src="https://github.com/user-attachments/assets/4e883524-1ea2-453d-a3e7-a16b1483fa30">

푸터 모바일
<img width="660" alt="image" src="https://github.com/user-attachments/assets/98b3f544-df61-4227-8333-cb8a5d9dfc0a">

# 리뷰 요청사항
- 16px 기준으로 작업하여 푸터 모바일 UI가 살짝 깨지고 있습니다

2024-08-11 18:01 UTC, rwaeng requested changes
푸터 만드느라 수고하셨습니다:)
미디어 쿼리 부분에서 모바일이랑 데스크탑 사이일 때 컴포넌트는 모바일처럼 쓰고 양 옆은 마진 주는 부분 수정하면서 코드 수정이 좀 있었는데 참고해서 수정해주세요! 늦게 적은 거라 코드가 깔끔하진 못한데,,, 반응형 부분은 제대로 동작할 거예요! 미디어 쿼리 관련 훅 사용해주셨는데 푸터에서는 안 쓰일지도 모르지만,,, 잘 쓸 수 있으면 좋을 거 같아요!!

수정 후에 리뷰 re-request 주세요!!

2024-08-12 03:05 UTC, yoonjin-C commented on src/components/common/Footer.jsx
> +        <S.IconWrapper>{isMobile ? <SmallBlog /> : <Blog />}</S.IconWrapper>
아 이게 크기를 조정해서 사용하려고 했는데 아이콘 크기 자체가 다른건지 적용이 안되더라고요.. @media 사용해서 width, height만 바꾸는게 아닌가요?

2024-08-12 03:40 UTC, rwaeng commented on src/components/common/Footer.jsx
> +        <S.IconWrapper>{isMobile ? <SmallBlog /> : <Blog />}</S.IconWrapper>
오엥! 왜 안 됐을까요 미디어 쿼리 사용해서 width, height만 바꾸면 되는 거 맞아요!

2024-08-12 04:54 UTC, rwaeng commented
확인했습니다~

2024-08-12 04:54 UTC, rwaeng approved these changes
확인했습니다~

2024-08-12 04:55 UTC, merged